[[pages]]
path = "app.py"
name = "SimulaÃ§Ãµes F1 2025"
icon = "ğŸï¸"

[[pages]]
path = "pages/1_Cenarios_Empate.py"
name = "CenÃ¡rios de Empate"
icon = "ğŸ"

[[pages]]
path = "pages/2_Cenarios_Campeao.py"
name = "CenÃ¡rios de CampeÃ£o"
icon = "ğŸ†"
